#########################################
#########################################

## RPECK 31/10/2022 - Statamic Push    ##

#########################################
#########################################

## Name ##
name: Push Statamic To Production & Staging

## Triggers ##
on:
  push:
    branches: ["master", "staging"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# Jobs
jobs:

  # Push
  push:
  
    # Name
    name: Push with SCP
  
    # OS
    runs-on: ubuntu-latest
    
    # Steps
    steps:
    
      # Target (Production)
      - name: Set Target (Default)
        run: |
          echo "TARGET=${{ secrets.TARGET }}" >> $GITHUB_ENV
          
      # Target (Staging)
      - name: Set Target (Staging)
        if: github.ref == 'refs/heads/staging'
        run: |
          echo "TARGET=${{ secrets.TARGET_STAGING }}" >> $GITHUB_ENV
    
      # Checkout Repo
      - uses: actions/checkout@v3
      
      # Composer
      - name: Composer
        uses: php-actions/composer@master
        with:
          dev: no
          args: --profile --ignore-platform-reqs
      
      # NPM
      - name: NPM
        uses: actions/setup-node@v3
      - run: |
          npm install
          npm run production --if-present
          
      # Remove .git
      - name: Remove Junk
        run: |
          rm -Rf .git*
          rm -Rf docker*
          rm -Rf DOCKER*
          rm -Rf *.log
          rm -Rf .env*
      
      # Upload SCP
      - name: Copy Files Via SCP
        uses: appleboy/scp-action@master
        with:
          host:             ${{ secrets.HOST }}
          username:         ${{ secrets.USERNAME }}
          port:             ${{ secrets.PORT }}
          key:              ${{ secrets.KEY }}
          passphrase:       ${{ secrets.PASSPHRASE }}
          target:           ${{ env.TARGET }}
          source:           ${{ github.workspace }}
          tar_tmp_path:     ~/tmp
          overwrite:        true
          strip_components: 2
          
      # Reload NGinx
      - name: Reload NGinx
        uses: appleboy/ssh-action@master
        with:
          host:        ${{ secrets.HOST }}
          username:    ${{ secrets.USERNAME }}
          port:        ${{ secrets.PORT }}
          key:         ${{ secrets.KEY }}
          passphrase:  ${{ secrets.PASSPHRASE }}
          script_stop: true
          script: |
            cd ${{ env.TARGET }}
            if ! test -f ".env"; then
              touch .env
              echo "APP_KEY=" >> .env
              sudo php artisan key:generate
              sudo php artisan config:cache
            fi
            sudo chown -R www-data:www-data .
            sudo find . -type f -exec chmod 664 {} \;   
            sudo find . -type d -exec chmod 755 {} \;
            sudo find . -type d -exec chmod g+s {} \;
            sudo chmod -R ug+rwx storage bootstrap/cache vendor
            sudo php please stache:clear
