#########################################
#########################################

## RPECK 31/10/2022 - Statamic Push    ##

#########################################
#########################################

## Name ##
name: Push Statamic To Production Server

## Triggers ##
on:
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# Jobs
jobs:

  # Push
  push:
  
    # Name
    name: Push with SCP
  
    # OS
    runs-on: ubuntu-latest
    
    # Steps
    steps:
    
      # Checkout Repo
      - uses: actions/checkout@v3
    
      # Cache
      - name: 🧯 Composer Dependency Cache
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      
      # Composer
      - name: Composer
        uses: php-actions/composer@master
      
      # NPM
      - name: NPM
        uses: actions/setup-node@v3
        with:
          cache: npm
      - run: |
          npm install
          npm run production --if-present
          
      # Remove .git
      - name: Remove Junk
        run: |
          rm -Rf .git*
          rm -Rf docker*
          rm -Rf DOCKER*
          rm -Rf *.log
          rm -Rf .env*
      
      # Upload SCP
      - name: Copy Files Via SCP
        uses: appleboy/scp-action@master
        with:
          host:             ${{ secrets.HOST }}
          username:         ${{ secrets.USERNAME }}
          port:             ${{ secrets.PORT }}
          key:              ${{ secrets.KEY }}
          passphrase:       ${{ secrets.PASSPHRASE }}
          target:           ${{ secrets.TARGET }}
          source:           ${{ github.workspace }}
          tar_tmp_path:     ~/tmp
          overwrite:        true
          strip_components: 2
          
      # Reload NGinx
      - name: Reload NGinx
        uses: appleboy/ssh-action@master
        with:
          host:        ${{ secrets.HOST }}
          username:    ${{ secrets.USERNAME }}
          port:        ${{ secrets.PORT }}
          key:         ${{ secrets.KEY }}
          passphrase:  ${{ secrets.PASSPHRASE }}
          script_stop: true
          script: |
            cd ${{ secrets.TARGET }}
            sudo chown -R ${{ secrets.USERNAME }}:www-data .
            sudo find . -type f -exec chmod 664 {} \;   
            sudo find . -type d -exec chmod 755 {} \;
            sudo find . -type d -exec chmod g+s {} \;
            sudo chmod -R ug+rwx storage bootstrap/cache
            sudo service nginx reload
